/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {},
    fontFamily: {
      sans: ["synonym", "sans-serif"],
      head: ["Chillax", "sans-serif"],
    },
    fontWeight: {
      light: "200",
      normal: "400",
      bold: "600",
      black: "800",
    },
    letterSpacing: {
      tight: "-.01em",
      normal: "0",
      wide: ".015em",
    },
    fontSize: {
      sm: "0.8rem",
      base: "1rem",
      lg: "1.563rem",
      xl: "2.441rem",
      "2xl": "3.052rem",
    },
    lineHeight: {
      sm: "1.12rem",
      base: "1.4rem",
      lg: "2.188rem",
      xl: "3.3174rem",
      "2xl": "4.273rem",
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          ...require("daisyui/src/theming/themes")["[data-theme=light]"],
          "base-100": "#e7e0eb",
          "base-200": "#f5f3f7",
          "base-300": "#d4c8db",
          primary: "#f24a71",
          "primary-content": "#f3f3f3",
          "primary-focus": "#e4335c",
          secondary: "#be5ae8",
          "secondary-content": "#f3f3f3",
          "secondary-focus": "#a841d4",
          accent: "#5960e8",
          "accent-content": "#f3f3f3",
          "accent-focus": "#eb7b7b",
          neutral: "#463764",
          "neutral-content": "#f3f3f3",
          "neutral-focus": "#2f214b",
          success: "#57D48E",
          "success-content": "#333333",
          info: "#63c6f7",
          "info-content": "#333333",
          warning: "#FFA743",
          "warning-content": "#333333",
          error: "#f36464",
          "error-content": "#333333",
        },
      },
      {
        dark: {
          ...require("daisyui/src/theming/themes")["[data-theme=dark]"],
          "base-100": "#16141e",
          "base-200": "#262330",
          "base-300": "#322e3c",
          "base-content": "#f3f3f3",
          primary: "#b73654",
          "primary-content": "#f3f3f3",
          "primary-focus": "#a32442",
          secondary: "#9c50bc",
          "secondary-content": "#f3f3f3",
          "secondary-focus": "#8537a6",
          accent: "#cc6666",
          "accent-content": "#f3f3f3",
          "accent-focus": "#c24848",
          neutral: "#383864",
          "neutral-content": "#f3f3f3",
          "neutral-focus": "#3f3f7f",
          success: "#71C483",
          "success-content": "#333333",
          info: "#74b7d4",
          "info-content": "#333333",
          warning: "#eda847",
          "warning-content": "#333333",
          error: "#c45757",
          "error-content": "#333333",
        },
      },
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    rtl: false,
    prefix: "",
    logs: false,
  },
};
