export class Genres {
  static readonly GENRES = [
    'action',
    'adventure',
    'arthouse',
    'biopic',
    'comedy',
    'crime',
    'detective',
    'drama',
    'erotic',
    'experimental',
    'fantasy',
    'historical',
    'horror',
    'musical',
    'mystery',
    'pornography',
    'romance',
    'science fiction',
    'silent',
    'suspense',
    'thriller',
    'war',
    'western',
    'noir',
  ];
  static readonly SUB_GENRES = [
    'absurdist',
    'alternate history',
    'autobiographical',
    'avant-garde',
    'black comedy',
    'body horror',
    'chamber drama',
    'comedy-drama',
    'coming-of-age',
    'contemporary fantasy',
    'cyberpunk',
    'dark fantasy',
    'docudrama',
    'dystopian',
    'found footage',
    'ghost',
    'high fantasy',
    'historical epic',
    'historical fiction',
    'home invasions',
    'legal drama',
    'medical drama',
    'melodrama',
    'mockumentary',
    'monster',
    'myth',
    'neo-noir',
    'nonlinear',
    'occult',
    'paranormal',
    'parody',
    'political',
    'post-apocalyptic',
    'psychological horror',
    'psychological thriller',
    'religious horror',
    'rom-coms',
    'satire',
    'slasher',
    'slice of life',
    'space opera',
    'splatter',
    'sport',
    'steampunk',
    'supernatural',
    'surrealist',
    'tech-noir',
    'techno-thriller',
    'teen drama',
    'urban fantasy',
    'utopian',
    'vampire',
    'werewolf',
    'zombies',
  ];

  static readonly ALL_TAGS = [
    'LGBT-related',
    'NASA',
    'actor',
    'adult',
    'alcoholism',
    'alien invasion',
    "alzheimer's disease",
    'animals',
    'anthropomorphic',
    'anti-fascism',
    'artificial intelligence',
    'astronauts',
    'augmented reality',
    'based on actual events',
    'based on real people',
    'biorobotics',
    'bisexuality',
    'bunker',
    'cancer',
    'cannibalism',
    'caste system',
    'child death',
    'child sexual abuse',
    'climate change',
    'cloning',
    'conspiracy theories',
    'consumerism',
    'contract killing',
    'cross-dressing',
    'cryonically preserved',
    'cult',
    'cyborgs',
    'deaf people',
    'death',
    'demons',
    'depression',
    'devil',
    'diarie',
    'dinosaurs',
    'disaster',
    'dissociative identity disorder',
    'dolls',
    'dragons',
    'dreams',
    'drugs',
    'dysfunctional families',
    'epic',
    'existentialist',
    'exorcism',
    'extraterrestrial life',
    'father–daughter relationships',
    'fictional planet',
    'freedom of speech',
    'galaxies',
    'gangsters',
    'genetic engineering',
    'genius',
    'genocide',
    'gothic',
    'hallucinogens',
    'hell',
    'high school',
    'holography',
    'homophobia',
    'human experimentation',
    'human sacrifice',
    'hypnosis',
    'idols',
    'improvised',
    'in outer space',
    'in the future',
    'in the middle ages',
    'incest',
    'intellectual disability',
    'intergalactic travel',
    'judge',
    'mad scientist',
    'mafia',
    'magic realism',
    'magical',
    'maniac',
    'mass murder',
    'mass surveillance',
    'medicine',
    'metaphysical',
    'midlife crisis',
    'mind control',
    'monks',
    'mother–son relationships',
    'musical groups',
    'mythology',
    'mythopoeia',
    'nanotechnology',
    'neo-nazism',
    'neopaganism',
    'nerds',
    'nudity',
    'ogrs',
    'on the Moon',
    'one-character',
    'orphans',
    'pacifists',
    'parallel universes',
    'philosophical',
    'pirates',
    'police',
    'postmodern',
    'post-traumatic stress disorder',
    'pregnancy',
    'prison',
    'propaganda',
    'prosthetic',
    'prostitution',
    'psychedelic',
    'psychiatry',
    'psychic power',
    'race-related controversies',
    'racism',
    'rape',
    'rebellion',
    'reincarnation',
    'revenge',
    'revolutionaries',
    'robot',
    'samurai',
    'schizophrenia',
    'school life',
    'serial killer',
    'sexuality',
    'singers',
    'social',
    'sorcery',
    'space',
    'spacecraft',
    'spirit possession',
    'spy',
    'stalking',
    'substance abuse',
    'suicide',
    'superhero',
    'teen',
    'terrorism',
    'time loop',
    'time travel',
    'totalitarianism',
    'troll',
    'unreliable narrator',
    'urban fantasy',
    'vegetarians',
    'veterans',
    'weapons of mass destruction',
    'weather hazard',
    'wedding',
    'witchcraft',
    'yakuza',
    'zoophilia',
  ];

  static readonly ALL_ANIME_GENRES = [
    'ecchi',
    'harem',
    'hentai',
    'isekai',
    'josei',
    'kodomo',
    'lolicon',
    'mecha',
    'seinen',
    'shōjo',
    'shōnen',
    'yaoi',
    'yuri',
  ];
  static readonly ALL_SERIES_GENRES = [
    'CGI',
    'clay animation',
    'dorama',
    'motion capture',
    'reboot',
    'remake',
    'sitcom',
    'spin-off',
    'stop-motion',
    'traditional animation',
  ];
  static readonly ALL_BOOK_GENRES = [
    'art',
    'astronomy',
    'biology',
    'chemistry',
    'classic',
    'cook',
    'engineering',
    'graphic novel',
    'guide',
    'health',
    'historical fiction',
    'history',
    'humor',
    'medicine',
    'memoir',
    'motivational',
    'physics',
    'psychology',
    'scientific popular',
    'self-help',
    'travel',
  ];

  static readonly ALL_TYPES = [
    'animated',
    'anime',
    'book',
    'cartoon',
    'comic',
    'dorama',
    'film',
    'manga',
    'manhwa',
    'movie',
    'novel',
    'graphic novel',
    'tv',
    'series',
    'non-fiction',
  ];
}
